# Generated by Django 4.1.4 on 2023-01-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to="fotos_user"),
        ),
    ]
