# Generated by Django 4.1.4 on 2023-01-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0002_alter_userprofile_foto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="fecha_nacimiento",
            field=models.DateField(null=True),
        ),
    ]
